#!/bin/bash

## Use these commands to create a sqlite mapping database
## You can also use phpLiteAdmin to maintain this database

# sqlite3 uid.db "create table uids (uid TEXT PRIMARY KEY,action TEXT);"
# sqlite3 uid.db "insert into uids (uid,action) values ('AA_BB_CC_DD','mpd/album:Wo  Wo ist Kartoffelbrei');"

action=`sqlite3 ../uid.db "select action from uids"`

echo $action
